ayasofyazilim-clomerce/ayasofyazilim-ui

package.json
src/organisms/header/header.stories.tsx
src/templates/dashboard/Dashboard.stories.tsx

fix:Type fixing.

---

src/molecules/avatar/avatar.stories.tsx
src/molecules/infocard/infocard.stories.tsx
src/organisms/card-list/cart-list.stories.tsx
src/organisms/country-selector/country-selector.stories.tsx
src/organisms/header/header.stories.tsx
src/pages/login/login.stories.tsx
src/pages/register/register.stories.tsx
src/templates/auth/auth.stories.tsx
src/templates/dashboard/dashboard.stories.tsx
src/templates/novel/custom-novel-editor.stories.tsx

This will allow us to use the folder system to name and categorize the stories
Reference: https://storybook.js.org/docs/writing-stories/naming-components-and-hierarchy

fix(storybook): remove titles

---

src/organisms/country-selector/index.tsx

- **feat(country-selector): tailwind direction support added**
- **feat(country-selector): tailwind direction support added**
- **fix:country-selector tailwind direction support (#13)**
- **chore: Github action auto lint**
- **chore:linting**
- **chore:linting**
- **chore:linting**
- **chore: add github token**
- **chore:token added**
- **chore:update token**
- **refactor(export): exports and ile structures changed**
- **fix: actions push**
- **fix(novel): css import path changed**
- **Update country-selector.stories.tsx**
- **fix(country-selector): import changed**
- **feat(country-selector): tailwind direction support added (#17)**
- **fix(country-selector): rtl support**

fix(country-selector):rtl support

---

src/templates/two-column-layout/index.tsx
src/templates/two-column-layout/two-column-layout.stories.tsx

- **feat(country-selector): tailwind direction support added**
- **feat(country-selector): tailwind direction support added**
- **refactor(export): exports and ile structures changed**
- **fix(novel): css import path changed**
- **Update country-selector.stories.tsx**
- **fix(country-selector): import changed**
- **feat(country-selector): tailwind direction support added (#17)**
- **feat(two column layout): two column layout added**

Two column layout

---

src/pages/login/login.stories.tsx
src/pages/register/register.stories.tsx

- **feat(country-selector): tailwind direction support added**
- **feat(country-selector): tailwind direction support added**
- **refactor(export): exports and ile structures changed**
- **fix(novel): css import path changed**
- **Update country-selector.stories.tsx**
- **fix(country-selector): import changed**
- **feat(country-selector): tailwind direction support added (#17)**
- **fix(country-selector): rtl support**
- **feat(template): add main layout (#20)**
- **feat(two column layout): two column layout added**
- **refactor(login): login form & login page rewritten**
- **fix(login form): imports fixed**
- **feat(login form): extra props & external form schema**
- **feat(register form): register form & page**
- **fix(login & register stories): stories edited**

Login & Register page

---

src/organisms/country-selector/index.tsx
tests/__snapshots__/CountrySelector.test.tsx.snap

- **feat(country-selector): tailwind direction support added**
- **feat(country-selector): tailwind direction support added**
- **fix:country-selector tailwind direction support (#13)**
- **chore: Github action auto lint**
- **chore:linting**
- **chore:linting**
- **chore:linting**
- **chore: add github token**
- **chore:token added**
- **chore:update token**
- **refactor(export): exports and ile structures changed**
- **fix: actions push**
- **fix(novel): css import path changed**
- **Update country-selector.stories.tsx**
- **fix(country-selector): import changed**
- **feat(country-selector): tailwind direction support added (#17)**
- **fix(country-selector): rtl support**
- **feat(template): add main layout (#20)**
- **feat(two column layout): two column layout added**
- …

fix:country-selector tooltip removed

---

src/molecules/navigation-menu/index.tsx
src/molecules/sheet/index.tsx
src/molecules/side-bar/index.tsx
src/organisms/burger-menu/burger-menu.stories.tsx
src/organisms/burger-menu/index.tsx
src/organisms/header/header.stories.tsx
src/organisms/header/index.tsx
src/templates/mainlayout/index.tsx

This PR add burger menu with it's animation, and refactored the related component for it.

feat: add burger menu item and it's story

---

src/molecules/forms/login-form/index.tsx
src/molecules/navigation-menu/index.tsx
src/molecules/navigation-menu/types.ts
src/organisms/burger-menu/index.tsx

This PR fixes few errors related to the UI which included: 
- added unique keys to login list
- added unique keys to ul elements
- removed unnecessary <a> tag to solve the hydration issue
- refactored the navigation types (WIP)
Related https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/17

fix: add keys to login form

---

src/molecules/about-card/about-card.stories.tsx
src/molecules/about-card/index.tsx

feat(about-card): add about card

---

src/molecules/card-image/card-image.stories.tsx
src/molecules/card-image/index.tsx

feat(card-image): add image component to use in card

---

src/molecules/card-image/card-image.stories.tsx
src/molecules/card-table/card-table.stories.tsx
src/molecules/card-tag/card-tag.stories.tsx
src/molecules/card-tag/index.tsx

feat: add tag component to use in card

---

src/molecules/card-tag/index.tsx
src/organisms/details-card/details-card.stories.tsx
src/organisms/details-card/index.tsx

add: detailed card component

---

src/templates/mainlayout/index.tsx

style: bg color and padding for scroll area

---

src/templates/section-layout/index.tsx
src/templates/section-layout/section-layout.stories.tsx

add: section layout

---

package.json
src/molecules/tables/columns.tsx
src/molecules/tables/data.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/organisms/card-list/card-list.stories.tsx
src/organisms/card-list/data.ts
src/templates/dashboard/dashboard.stories.tsx
src/templates/dashboard/index.tsx
src/templates/dashboard/types.ts

This PR add tables to the project with ability to set the columns headers,customize them and with examples.

feat: add tables option to the UI

---

src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/templates/dashboard/index.tsx

This PR Add table action that allows you to create new table element based on it.

feat: add table action

---

src/organisms/details-card/compact-vertical.tsx
src/organisms/details-card/compact.tsx
src/organisms/details-card/full-page.tsx

DetailsCard variants updated due CardsTable update

feat:DetailsCard variants

---

src/molecules/dialog/dialog.stories.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/utils.ts
src/templates/dashboard/index.tsx

Add data table with ability to delete and edit the data in the row.

feat: implement data tables v0.2

---

src/molecules/infocard/index.tsx
src/molecules/infocard/infocard.stories.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/organisms/card-list/index.tsx
src/templates/dashboard/dashboard.stories.tsx
src/templates/dashboard/index.tsx
src/templates/dashboard/types.ts

This PR adds the ability to show the loading state of a table. 
Video:
https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/assets/18273833/007195bc-cfd3-4611-b6bb-4428559d3eb0
Closes https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/issues/143

feat(tables): Add loading state

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

Fixes https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/issues/293

feat: add action list to table

---

.github/pull_request_template.md
src/lib/json-to-csv/index.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

Allowed the user to have multiple actions and enabled

fix(tables): enable forms in actions

---

.github/workflows/main.yml

This pull request enables the lint action on pull requests.
Was not tested yet.
Nothing related to UI to show.

ci: enable on pull requests

---

src/molecules/dialog/index.tsx

chore: export tableAction

---

package.json
src/hooks/useDebounce.ts

feat: add useDebounce hook

---

src/molecules/tables/index.tsx

feat: add serverside filtering

---

src/molecules/dialog/dialog.stories.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

chore: rename types

---

src/molecules/tables/columns.tsx
src/molecules/tables/index.tsx

fix: editable

---

src/molecules/tables/filter-colum.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/templates/dashboard/dashboard.stories.tsx
src/templates/dashboard/index.tsx

feat: add detailed filters to table

---

src/molecules/tables/filter-colum.tsx

chore: function calls

---

src/molecules/tables/filter-colum.tsx
src/molecules/tables/index.tsx

style: table filters  #327

---

src/molecules/tables/data.tsx

chore: update type

---

package.json
src/lib/create-zod-object/index.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

This pr update the imports of the files

chore: update imports

---

package.json
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

refactor: Autoform

---

src/molecules/tables/filter-colum.tsx

chore: replace Calendar with Advanced Calendar

---

src/molecules/tables/filter-colum.tsx

chore: remove unused codes

---

src/molecules/tables/index.tsx

fix: make dialogDescription and dialogTitle as optional

---

src/molecules/tables/columnsGenerator.tsx

chore: remove delete role and make it  as  delete

---

src/molecules/issue-form/data.ts
src/molecules/issue-form/index.tsx
src/molecules/issue-form/issueForm.stories.tsx
src/molecules/issue-form/type.ts

This PR adds the props to the issue form; nothing changed in terms of style or design.

feat: add tags props

---

src/molecules/issue-form/index.tsx

chore(issue-form): export types

---

.github/workflows/publish.yml

This PR updates the demo website whenever we push something on main.

ci: update the website on main

---

.github/workflows/publish.yml

ci: update website on push to main

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx

feat:tableColumns sort feature with positions prop

---

src/lib/create-zod-object/index.tsx

chore:update createZodObject

---

src/molecules/tables/columnsGenerator.tsx

fix: missing function return added

---

@/components/ui/date-picker.tsx
src/organisms/auto-form/auto-form.stories.tsx
src/organisms/auto-form/fields/object.tsx
src/organisms/auto-form/fields/phone.tsx
src/organisms/auto-form/index.tsx
src/organisms/auto-form/types.ts

feat:Autoform,Datepicker disabled and className props

---

src/molecules/tables/data.tsx
src/molecules/tables/filter-colum.tsx
src/molecules/tables/tables.stories.tsx

Datatable detailed filters extended with select & boolean & number options.

feat:DetailedFilter>select&boolean filters

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

feat:DataTable selectable prop

---

src/molecules/dialog/dialog.stories.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/columns.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

refactor: table actions

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

chore: remove unused props removed

---

src/molecules/tables/index.tsx

chore: table remove default delete action

---

src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx

chore: simplfy table action dialog

---

src/molecules/dialog/dialog.stories.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx

feat:autoform dialog submit props & inital values

---

src/organisms/auto-form/fields/checkbox.tsx
src/organisms/auto-form/fields/date.tsx
src/organisms/auto-form/fields/enum.tsx
src/organisms/auto-form/fields/file.tsx
src/organisms/auto-form/fields/input.tsx
src/organisms/auto-form/fields/number.tsx
src/organisms/auto-form/fields/radio-group.tsx
src/organisms/auto-form/fields/switch.tsx
src/organisms/auto-form/fields/textarea.tsx

fix:prevent containerClassName param from childs

---

src/organisms/auto-form/fields/checkbox.tsx
src/organisms/auto-form/fields/date.tsx
src/organisms/auto-form/fields/enum.tsx
src/organisms/auto-form/fields/file.tsx
src/organisms/auto-form/fields/input.tsx
src/organisms/auto-form/fields/number.tsx
src/organisms/auto-form/fields/radio-group.tsx
src/organisms/auto-form/fields/switch.tsx
src/organisms/auto-form/fields/textarea.tsx

chore: autoform fields typo

---

src/organisms/auto-form/fields/input.tsx

chore:remove unnecessary wrapper

---

src/molecules/issue-form/cards.tsx
src/molecules/issue-form/index.tsx

This PR unifies the cards in one component.

chore(issue-form): use one component for cards

---

src/molecules/tables/index.tsx

chore: rename type

---

src/molecules/issue-form/index.tsx

chore: change import

---

.github/pull_request_template.md
src/molecules/dialog/index.tsx

fix:values override fixed

---

src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/templates/dashboard/dashboard.stories.tsx

refactor: add actionList for custom column type

---

src/organisms/auto-form/index.tsx

style: add h-full to autoform

---

src/molecules/page-header/index.tsx
src/molecules/page-header/page-header.stories.tsx

feat: add back button to page header

---

src/molecules/page-header/index.tsx
src/molecules/page-header/page-header.stories.tsx

refactor: page header

---

src/molecules/page-header/index.tsx

style: page header

---

src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/fields/checkbox.tsx
src/organisms/auto-form/fields/switch.tsx
src/organisms/auto-form/index.tsx

chore:autoform

---

src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx

feat:action text

---

src/molecules/tables/index.tsx

fix: cta toString not a function & fix word wrap

---

src/organisms/auto-form/common/tooltip.tsx

fix:(autoform) div cant be child of p

---

src/lib/create-zod-object/index.tsx

feat: add subPositions to autoform

---

src/molecules/tables/index.tsx

style: table

---

src/molecules/tree-view/tree-view-api.tsx

chore: translate

---

package.json

chore:package update

---

src/molecules/file-uploader/empty-card.tsx

chore: remove icon

---

package.json
pnpm-lock.yaml

chore:libphone version

---

src/molecules/file-uploader/index.tsx

feat(FileUploader): language support

---

@/components/ui/skeleton.tsx
src/molecules/page-header/index.tsx
src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/fields/checkbox.tsx
src/organisms/auto-form/fields/date.tsx
src/organisms/auto-form/fields/enum.tsx
src/organisms/auto-form/fields/file.tsx
src/organisms/auto-form/fields/input.tsx
src/organisms/auto-form/fields/number.tsx
src/organisms/auto-form/fields/object.tsx
src/organisms/auto-form/fields/phone.tsx
src/organisms/auto-form/fields/radio-group.tsx
src/organisms/auto-form/fields/switch.tsx
src/organisms/auto-form/fields/textarea.tsx
src/organisms/auto-form/index.tsx
src/organisms/auto-form/types.ts

feat(autoform): isLoading prop

---

src/molecules/tables/index.tsx

feat(DataTable): className support & loading state management

---

src/lib/create-zod-object/index.tsx

chore:relocate prop position

---

src/molecules/file-uploader/index.tsx

chore(FileUploader): make resources prop optional

---

src/molecules/file-uploader/index.tsx

chore(FileUploader): import path

---

src/organisms/auto-form/fields/object.tsx

feat: add ClassName inside fieldConfig in autoform

---

src/organisms/auto-form/fields/checkbox.tsx
src/organisms/auto-form/fields/date.tsx
src/organisms/auto-form/fields/enum.tsx
src/organisms/auto-form/fields/file.tsx
src/organisms/auto-form/fields/input.tsx
src/organisms/auto-form/fields/number.tsx
src/organisms/auto-form/fields/radio-group.tsx
src/organisms/auto-form/fields/switch.tsx
src/organisms/auto-form/fields/textarea.tsx

fix(Autoform):isLoading prop deleted before element render

---

@/components/ui/breadcrumb.tsx

fix: type error on breadcrumb

---

src/molecules/tables/index.tsx

fix(table): show view and default actions if one is provided

---

src/templates/section-layout-v2/index.tsx

style: section-layout-v2

---

src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

feat: add type to confirmation dialog description

---

src/molecules/tables/index.tsx
src/organisms/auto-form/index.tsx
src/templates/section-layout-v2/index.tsx

style: table & autoform & section-layout-v2

---

src/molecules/issue-form/index.tsx

chore: issue form overflow

---

package.json
pnpm-lock.yaml

chore: update lucide-react

---

src/lib/create-zod-object/index.tsx

feat(createZodObject): string enum support

---

src/organisms/auto-form/auto-form.stories.tsx
src/organisms/auto-form/fields/enum.tsx
src/organisms/auto-form/index.tsx
src/organisms/auto-form/types.ts
src/organisms/auto-form/utils.ts

feat(Autoform): enum options label override

---

src/molecules/dialog/index.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

chore: fix typo of tableAction -> componentType

---

src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

chore: remove unused title prop on TableActionConfirmation

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/field.tsx
src/organisms/schema-form/utils.ts

fix(SchemaForm):uiSchema merge fix

---

src/organisms/schema-form/fields/checkbox.tsx
src/organisms/schema-form/fields/date.tsx
src/organisms/schema-form/fields/error.tsx
src/organisms/schema-form/fields/phone.tsx
src/organisms/schema-form/fields/select.tsx
src/organisms/schema-form/fields/text.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/utils.ts

feat(SchemaForm): fix & feat & chore

---

src/lib/create-zod-object/index.tsx

feat(AutoForm): proper error message for missing property

---

src/organisms/auto-form/index.tsx

chore(AutoForm): unify types for consistency

---

src/lib/create-zod-object/index.tsx

fix(CreateZodObject): array subpositions

---

src/organisms/auto-form/utils.ts

fix:additionalProperties type can be object

---

src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/utils.ts

fix(AutoForm):createFieldConfigWithResource

---

src/organisms/auto-form/utils.ts

fix(AutoForm): mergeFieldConfigs

---

src/organisms/auto-form/utils.ts

feat(AutoformUtils): createFieldConfigWithResource

---

src/organisms/auto-form/utils.ts

feat(Autoform): createFieldConfigWithResource

---

src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/fields/object.tsx
src/organisms/auto-form/fields/object_acc.tsx
src/organisms/auto-form/types.ts
src/organisms/auto-form/utils.ts

feat(Autoform): array button fieldConfig support

---

src/molecules/multi-select/index.tsx
src/molecules/multi-select/multi-select.stories.tsx

feat: add multi-select

---

src/organisms/auto-form/utils.ts

fix(dashboard): add object control to fix the error of (Cannot read properties of undefined (reading 'type'))

---

src/molecules/dialog/index.tsx
src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/fields/custom-combobox.tsx
src/organisms/auto-form/fields/index.tsx
src/organisms/auto-form/fields/object.tsx
src/organisms/auto-form/index.tsx
src/organisms/auto-form/types.ts
src/organisms/auto-form/utils.ts

feat(Autoform):ComboboxField & SortableFields & Renderer

---

CONTRIBUTING.md

doc: add contributing guide

---

src/organisms/auto-form/fields/custom-combobox.tsx

feat(Autoform):CustomCombobox onValueChange

---

@/components/ui/useMediaQuery.ts
src/organisms/auto-form/fields/custom-combobox.tsx

feat(Autoform):CustomCombobox responsive component

---

src/molecules/tables/index.tsx

chore: make improvments on table detailed filter

---

src/molecules/tables/index.tsx

chore: export type filter column result

---

src/organisms/auto-form/fields/array.tsx
src/organisms/auto-form/fields/object.tsx
src/organisms/auto-form/types.ts
src/organisms/auto-form/utils.ts

fix(Autoform): unnecesary separator

---

src/molecules/tables/index.tsx

feat(DataTable): classNames

---

src/molecules/tables/filter-column.tsx

fix: filter dropdown is visible for default filters

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/tables.stories.tsx

feat: custom filter initial code

---

src/lib/create-zod-object/index.tsx
src/organisms/auto-form/fields/number.tsx
src/organisms/auto-form/fields/object.tsx

style(Autoform): className prop & number styles

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/stories/schema-form.stories.tsx
src/organisms/schema-form/types.ts
src/organisms/schema-form/utils.ts

feat(SchemaForm): filters for schema

---

src/molecules/tables/index.tsx
src/templates/dashboard/index.tsx

Changes:
1. The cards and table are aligned together.
2. I have improved the cards class
...
| Before | After |
|--------|-------|
|<img width="336" alt="Screenshot 2024-10-20 at 5 38 17 PM" src="https://github.com/user-attachments/assets/ae3293b3-7fb4-4eb8-af95-c977a7689af8">|<img width="336" alt="Screenshot 2024-10-20 at 5 38 45 PM" src="https://github.com/user-attachments/assets/6d269605-34c9-4eba-8f34-e28d54fec923">|

style(dashboard): better padding for card list and table 

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

- showed selected elements as badges 
- prevent showing the id on the filter badge 
- prevent adding the same element to the badges

feat(table): add badges to selected async filter

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/types.ts

feat(SchemaForm): no hardcoded submit text from now on

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/index.tsx
src/organisms/schema-form/widgets/password.tsx

feat(SchemaForm):Password Input

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx

feat(table): async-select add select all

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/array.tsx
src/organisms/schema-form/types.ts

feat(SchemaForm): useScrollArea & type export fix

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/tables.stories.tsx

feat(table): use props for async filter

---

src/molecules/tables/tables.stories.tsx
src/organisms/schema-form/templates/array.tsx
src/organisms/schema-form/utils.ts
src/organisms/schema-form/widgets/date.tsx

fix(SchemaForm): Resource resolver array items issue

---

src/molecules/tables/index.tsx

 chore: split the select to array

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/text.tsx

chore(SchemaForm): input type & children style

---

src/organisms/schema-form/types.ts
src/organisms/schema-form/utils.ts

feat(SchemaForm):bulkCreateUiSchema

---

src/organisms/schema-form/widgets/checkbox.tsx
src/organisms/schema-form/widgets/combobox.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx
src/organisms/schema-form/widgets/date.tsx
src/organisms/schema-form/widgets/password.tsx
src/organisms/schema-form/widgets/select.tsx
src/organisms/schema-form/widgets/switch.tsx
src/organisms/schema-form/widgets/text.tsx

feat(SchemaForm): disabled prop

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/types.ts
src/organisms/schema-form/utils.ts

feat(SchemaForm):sortable filters

---

src/organisms/schema-form/widgets/custom-combobox.tsx

feat(SchemaForm):custom combobox onchange support

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx

!table(filters): change the fetch data to filter component

---

src/molecules/tables/index.tsx
src/organisms/auto-form/fields/custom-combobox.tsx

feat(table): allow custom table action to open as sheet & fix(custom-combobox):when selectIdentifier is number, string does not equals number error 

---

src/organisms/schema-form/templates/array.tsx
src/organisms/schema-form/templates/field.tsx
src/organisms/schema-form/templates/object.tsx

feat(SchemaForm): field & object style

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/array.tsx

chore(SchemaForm):disabled props for array & submit button

---

src/organisms/schema-form/templates/object.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx

style: fix label position if contrainer grid

---

src/molecules/tables/filter-column.tsx

feat(table): close async filter on save

---

src/templates/section-layout-v2/index.tsx

feat(SectionLayoutV2): className & children props for section navbar

---

package.json
pnpm-lock.yaml
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts

feat: add Tanstack Table & fix storybook

---

package.json
src/molecules/dialog/dialog.stories.tsx
src/molecules/dialog/index.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts
src/templates/dashboard/types.ts

This PR extract the types from the table code and create a separate file for them. 
similar to the work that @ecbakas  has done before.

chore(table): seperate types from the code

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-pagination.tsx
src/molecules/tanstack-table/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/tanstack-table-view-options.tsx
src/molecules/tanstack-table/types.ts

feat(tanstack-table): add toolbar & rename types & rename components 

---

src/molecules/dialog/index.tsx
src/molecules/tables/filter-column.tsx
src/molecules/tables/helper-components.tsx
src/molecules/tables/index.tsx
src/molecules/tables/table-footer.tsx
src/molecules/tables/table-toolbar.tsx

In this PR I did not change or update any functionality.

refactor(table): extract functions to clearify reading the table

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): make columns pinnable

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-filter-text.tsx
src/molecules/tanstack-table/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/types.ts

feat(tanstack-table): add filtering opportunity to text based columns

---

src/molecules/tanstack-table/tanstack-table-filter-faceted.tsx
src/molecules/tanstack-table/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/types.ts

feat(tanstack-table): add filtering opportunity to select based columns

---

src/organisms/schema-form/index.tsx

fix(SchemaForm):validator additional properties

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts

feat(tanstack-table): add excluding columns opportunity

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx

refactor(table): extract actions functions 

---

src/molecules/tanstack-table/tanstack-table-column-header.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): add tanstackTableCreateColumns by row data & translatable column title

---

src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): make column linkable by another column

---

src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): make columns faceted & replace a tag with Next Link

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts

I added a prop to show and hide actions.
I tested it locally on my pc
Before this PR we did not hide actions at all. 
Hide Action True: 
Hide Action False:

feat(table): hide/show actions props

---

src/molecules/tables/table-footer.tsx

chore: allow editable with pagination, disable next/prev on loading

---

src/molecules/tables/table-footer.tsx

feat(table): add pagination and rows per page

---

src/molecules/dialog/index.tsx
src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tables/table-footer.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts

Chore(table): change sheetside, style, and loading state

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-confirmation.tsx
src/molecules/tanstack-table/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/types.ts

feat(tanstack-table): add row actions dropdown & add confirmation dialog action

---

src/molecules/combobox/index.tsx

feat: Combobox

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-autoform-dialog.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-custom-dialog.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): add autoform row action & update storybook

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/types/index.ts

refactor(SchemaForm): submit props

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/tanstack-table-view-options.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

Action appears when you select a row.

feat(tanstack-table): add selected row action & selectable rows & primary action

---

src/organisms/schema-form/index.tsx

feat(SchemaForm): Make form controlled

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-pagination.tsx
src/molecules/tanstack-table/tanstack-table-table-actions-autoform-dialog.tsx
src/molecules/tanstack-table/tanstack-table-view-options.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx

feat(tanstack-table): add table autoform dialog & show selected row count & style table

---

src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

style(tanstack-table): add className & iconClassName props

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-autoform-dialog.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-confirmation.tsx
src/molecules/tanstack-table/tanstack-table-row-actions-custom-dialog.tsx
src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): add badge to columns & column ordering

---

src/molecules/combobox/index.tsx

feat(Combobox): custom error message

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table-table-actions-autoform-dialog.tsx
src/molecules/tanstack-table/tanstack-table-table-actions-custom-dialog.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx

feat(tanstack-table): add TableCustomDialog & update stories

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types.ts
src/molecules/tanstack-table/utils.tsx

feat(tanstack-table): pinnable columns

---

src/molecules/tanstack-table/tanstack-table-row-actions.tsx

chore: actions instread of dot

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx

feat(tanstack-table): add columnVisibility

---

src/molecules/tables/cells.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts

feat(table): improve custom cells options

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx

feat(TanstackTable): customColumns date option.

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/types.ts

feat(table-date): add localization

---

src/molecules/tanstack-table/index.tsx

feat(tanstack-table): server side pagination

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columnNames.ts
src/molecules/tanstack-table/utils/index.tsx

feat(TanstackTable): columnName utils & link style & cell className

---

src/molecules/tanstack-table/types/index.ts

chore:(TanstackTable): more badge value type

---

src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columnNames.ts
src/molecules/tanstack-table/utils/index.tsx

feat(TanstackTable): icon custom cell

---

src/molecules/tanstack-table/fields/tanstack-table-filter-faceted.tsx
src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx

feat(tanstack-table): server side filtering

---

src/molecules/tanstack-table/types/index.ts

refactor(TanstackTable): import location

---

src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx

feat(TanstackTable): multiple badges.

---

src/molecules/dialog/index.tsx
src/molecules/tables/types.ts

fix(dialog): close autoform on submit

---

src/organisms/auto-form/fields/custom-combobox.tsx

feat: add disabled to CustomCombobox

---

src/molecules/tanstack-table/utils/index.tsx

fix(TanstackTable): multiple badges couses multiple content

---

src/organisms/auto-form/config.ts
src/organisms/auto-form/fields/password.tsx
src/organisms/auto-form/types.ts

feat(autoform/password): add password input to the autoform

---

src/molecules/tables/index.tsx

chore: add fetch request

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/stories/schema-form.stories.tsx
src/organisms/schema-form/types/index.ts
src/organisms/schema-form/utils/index.ts

feat(SchemaForm): typesafe filters & removeFields from schema by default 

---

src/molecules/tables/table-pagination.tsx

fix(Table): pagination total page count

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts

fix(table): select issue when page change & remove console log

---

src/molecules/tanstack-table/fields/tanstack-table-filter-faceted.tsx
src/molecules/tanstack-table/fields/tanstack-table-filter-text.tsx
src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/types/index.ts

refactor(tanstack-table): faceted & text filter params handling

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions-custom-dialog.tsx
src/molecules/tanstack-table/fields/tanstack-table-table-actions-custom-dialog.tsx

fix(TanstackTable): do not create dialog footer if there is no children

---

src/molecules/tables/columns.tsx
src/molecules/tables/index.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts
src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx

feat(TanstackTable): default cell converters & feat(DataTable): renderSubComponent typesafe

---

src/molecules/dialog/index.tsx
src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/index.tsx
src/molecules/tables/table-toolbar.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types.ts

feat(table): pass trigger data to dialog

---

src/molecules/tanstack-table/tanstack-table.stories.data.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

feat(TanstackTable): typesafe column generator

---

src/molecules/tanstack-table/types/index.ts

chore(tanstack-table): add TanstackTableCreationProps

---

src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx

chore(tanstack-table): check is column exist

---

src/molecules/tanstack-table/fields/tanstack-table-filter-date.tsx
src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx
src/molecules/tanstack-table/types/index.ts

feat(tanstack-table): add date filter

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx
src/molecules/tanstack-table/utils/pinning-styles.ts

feat(TanstackTable): custom cell & filler column

---

src/molecules/infocard/index.tsx
src/templates/dashboard/index.tsx

style(infocard): make it compact

---

src/molecules/tanstack-table/utils/columns-by-row-data.tsx

chore(tanstack-table): faceted boolean type handler

---

src/molecules/tanstack-table/fields/tanstack-table-view-options.tsx

refactor(TanstackTable): set button types for in-form usage

---

src/molecules/dialog/index.tsx

fix(autoform): make the cta and description appear in the autoform

---

.eslintrc.js
src/molecules/tables/index.tsx
src/molecules/tanstack-table/fields/tanstack-table-view-options.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(tanstack-table): allow adding new row on edit mode

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

chore(tanstack-table): hide invalid date

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(TanstackTable): delete row action & editable flag 

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/index.tsx

feat(Tanstack): single action render & hide actions column header

---

src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(TanstackTable): format editable column value with schema type

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts

feat:(TanstackTable): editable onTableDataChange

---

src/organisms/schema-form/custom/table-field.tsx
src/organisms/schema-form/fields/error.tsx
src/organisms/schema-form/fields/index.tsx

feat(SchemaForm): TableField & ErrorSchemaTemplate

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts

feat:(TanstackTable): showPagination flag, default=true

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(tanstacktable): add boolean support for edit & fix render problem on updateData

---

src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

fix(tanstacktable): initial value zero problem

---

src/molecules/confirm-dialog/confirm-dialog.story.tsx

chore:update old story title

---

src/organisms/schema-form/templates/array.tsx

feat(SchemaForm): addable option for array

---

src/organisms/schema-form/custom/table-field.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/array.tsx

style(SchemaForm): wrapper & array & table field

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/stories/schema-form.stories.tsx
src/organisms/schema-form/types/index.ts

feat(SchemaForm): onSubmit & onChange typesafe

---

.eslintrc.js
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/index.tsx
src/molecules/tanstack-table/utils/table.tsx
src/organisms/schema-form/custom/table-field.tsx

refactor(tanstack-table): editable table & non editable table props are divided & id problem solved & many refactor

---

src/molecules/multi-select/multi-select.stories.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/utils/columns-by-row-data.tsx
src/molecules/tanstack-table/utils/table.tsx
src/organisms/auto-form/utils.ts
src/organisms/schema-form/fields/phone.tsx

chore:remove console log

---

src/organisms/schema-form/fields/error.tsx
src/organisms/schema-form/types/index.ts

feat(SchemaForm): make filter keys generic & key to errors

---

src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx

refactor(tanstackTable): add style as p-px

---

src/molecules/tables/columnsGenerator.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types/index.ts

feat(customComponent): add setIsOpen to make the customComponent be closed after submit

---

src/molecules/forms/register-form/index.tsx

chore(signup): disable buttons on loading

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts

chore(tanstack-table): missing excludeColumns prop

---

src/molecules/tanstack-table/index.tsx

chore(tanstack-table): missing filter prop

---

src/molecules/confirm-dialog/index.tsx

feat(ConfirmDialog): update props

---

src/molecules/confirm-dialog/confirm-dialog.stories.tsx
src/molecules/confirm-dialog/index.tsx

feat: confirm dialog props

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(TanstacTable): filter editable columns by prop

---

src/molecules/tables/filter-column.tsx
src/molecules/tables/index.tsx
src/molecules/tables/table-toolbar.tsx
src/molecules/tables/tables.stories.tsx
src/molecules/tables/types/index.ts

feat(table-filter): add left side menu

---

src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/tanstack-table.stories.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

feat(TanstactTable): editable table object & enum handle

---

src/molecules/advanced-calendar/index.tsx
src/organisms/schema-form/widgets/date.tsx

feat(SchemaForm): use advanced datepicker

---

src/molecules/tables/index.tsx

style: tables full width

---

src/molecules/dialog/index.tsx

fix(autoform): make the data come in edit form

---

@/lib/utils.ts
src/molecules/advanced-calendar/index.tsx
src/molecules/button/index.tsx
src/molecules/combobox/index.tsx
src/molecules/confirm-dialog/index.tsx
src/molecules/multi-select/index.tsx
src/molecules/numeric-input/index.tsx
src/molecules/page-header/index.tsx
src/molecules/spinner/index.tsx
src/molecules/tanstack-table/fields/tanstack-table-filter-faceted.tsx
src/molecules/tanstack-table/utils/cell-with-actions.tsx
src/molecules/tanstack-table/utils/columns-by-row-data.tsx
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx
src/molecules/tanstack-table/utils/index.tsx
src/molecules/tanstack-table/utils/table.tsx
src/molecules/tracker/index.tsx
src/organisms/card-list/index.tsx
src/organisms/header/index.tsx
src/organisms/profile-menu/index.tsx
src/organisms/schema-form/custom/table-field.tsx
src/organisms/schema-form/fields/index.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/index.tsx
src/organisms/schema-form/utils/index.ts
src/organisms/schema-form/widgets/index.tsx

chore(ui): add use client

---

src/templates/tab-layout/index.tsx

style(TabLayout): classNames & orientation

---

src/templates/tab-layout/index.tsx

feat(TabLayout): classNames props & styles

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

feat(TanstackTable): badge position prop

---

src/molecules/multi-select/index.tsx
src/organisms/auto-form/fields/object.tsx

refactor(autoform/array): make the autoform read the array

---

src/molecules/multi-select/index.tsx

fix(autoform/array): make the multiSelect work in create and update forms

---

src/molecules/infocard/index.tsx

chore(infocard): add className to parent

---

src/molecules/tanstack-table/fields/tanstack-table-filter-faceted.tsx
src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx

fix(tanstack-table): faceted filter translation

---

src/organisms/schema-form/index.tsx

feat(SchemaForm): scrollarea table to block

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx
src/organisms/schema-form/widgets/date.tsx

fix(SchemaForm): horizontal scroll & emptyValue & undefined value

---

src/molecules/tables/types/index.ts

chore: add missing addRow type

---

src/molecules/multi-select/index.tsx

chore(multi Select): add w-full size to select field

---

src/molecules/combobox/index.tsx
src/organisms/schema-form/widgets/combobox.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx

chore:combobox field empty value

---

src/molecules/combobox/index.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/date.tsx

chore: combobox field value 

---

src/organisms/schema-form/widgets/date.tsx

feat(SchemaForm): datepicker disabled dates

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

feat(tanstack-table): add onSelectedRowChange

---

src/organisms/auto-form/common/tooltip.tsx

style: remove darkmode from autoform tooltip

---

src/molecules/tanstack-table/fields/tanstack-table-toolbar.tsx

style(tanstack-table): filters are overflowing on small screens

---

src/molecules/forms/login-form/index.tsx
src/molecules/forms/login-form/login-form.stories.tsx

feat:login form default values

---

src/molecules/tanstack-table/fields/tanstack-table-table-actions-autoform-dialog.tsx
src/molecules/tanstack-table/types/index.ts

chore(autoform-dialog): add fielconfig

---

src/molecules/tables/columnsGenerator.tsx

feat: check is navigator.clipboard available

---

src/organisms/schema-form/types/index.ts
src/organisms/schema-form/utils/index.ts
src/organisms/schema-form/utils/password-validate.ts

feat(SchemaForm): custom validation & password match validate

---

src/templates/tab-layout/index.tsx

style: tab layout overflow y on vertical

---

src/molecules/page-header/index.tsx

[#1053](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1053)
via @ahmeterenodaci

feat:  if hasReferer redirect with it (window.history.back)

---

src/molecules/tanstack-table/fields/tanstack-table-pagination.tsx
src/molecules/tanstack-table/index.tsx

style: tanstack table

---

package.json
pnpm-lock.yaml

chore: update react and react-dom types

---

@/lib/utils.ts
src/organisms/schema-form/widgets/index.tsx
src/organisms/schema-form/widgets/multi-select.tsx

refactor: remove unnecessary 'use client' directive from utils.ts

---

src/molecules/async-command/index.tsx

feat: add async command

---

src/organisms/schema-form/widgets/select.tsx

fix(Schema Form): make the select work from int to string

---

@/components/ui/popover.tsx
src/molecules/async-select/index.tsx
src/molecules/multi-select/index.tsx

feat(async-select): add async select & remove async command

---

src/molecules/action-button/index.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/email.tsx
src/organisms/schema-form/widgets/index.tsx

feat(Schema Form): add email field

---

src/molecules/async-select/index.tsx

feat(async-select): add disabled property

---

src/molecules/combobox/index.tsx

feat(combobox): add optional id prop to CustomComboboxProps

---

src/molecules/filter-component/index.tsx

feat(FilterComponent): implement filter component with date, multi, and async selects

---

src/templates/tab-layout/index.tsx

feat(tab-layout): implement variant and orientation support for tabs

---

src/templates/tab-layout/index.tsx

feat(tab-layout): enhance active tab detection with search parameters

---

src/molecules/page-header/index.tsx

fix(page-header): improve referer detection logic for better reliability

---

src/molecules/tanstack-table/utils/columns-by-row-data.tsx

feat(table): improve icon positioning and spacing in cell rendering

---

src/molecules/filter-component/index.tsx
src/molecules/tanstack-table/types/index.ts

fix(table): update dateOptions type to Intl.DateTimeFormatOptions

---

src/molecules/multi-select/index.tsx
src/organisms/schema-form/widgets/multi-select.tsx

feat(multi select): add title to fields

---

src/molecules/multi-select/index.tsx
src/organisms/schema-form/widgets/multi-select.tsx

feat(multi select): add title

---

src/templates/tab-layout/index.tsx

fix(tab-layout): enhance active tab detection logic for improved

---

src/molecules/tanstack-table/utils/columns-by-row-data.tsx

fix(columns-by-row-data): simplify value retrieval and remove debug log

---

@/components/ui/chart.tsx
package.json
pnpm-lock.yaml

fix(dependencies): add @types/chart.js and moment to pnpm-lock.yaml

---

@/components/ui/chart.tsx
package.json

fix: update import paths and unify string quotes for consistency

---

src/organisms/schema-form/widgets/date.tsx

refactor(date cmponent): enhance the view & add select month and year

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/types/index.ts

feat(tanstack): add conditon option to row actions

---

src/molecules/page-header/index.tsx
src/molecules/page-header/page-header.stories.tsx

refactor(page-header): change export to default function syntax

---

src/organisms/schema-form/widgets/custom-combobox.tsx

refactor(CustomComboboxWidget): solve _i_selectIdentifier.toLocaleLowerCase is not a function error  when id is a number

---

src/molecules/forms/forgot-password-form/forgot-password-form.stories.tsx
src/molecules/forms/forgot-password-form/index.tsx

refactor(forgot-password-form): add tenant field to schema and form

---

src/organisms/schema-form/templates/object.tsx

refactor(object-field-template): replace fieldset with div

---

src/molecules/tanstack-table/fields/tanstack-table-view-options.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

feat(tanstack table): add disable for select & fix save button to send all the selected rows

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/index.tsx
src/organisms/schema-form/widgets/textarea.tsx

feat(schema-form): add custom textarea input widget

---

src/organisms/auto-form/index.tsx

fix(auto-form): ignore TypeScript error for form resolver

---

src/templates/tab-layout/index.tsx

feat(tab-layout): add support for disabled tabs in TabLayout component

---

src/molecules/date-picker/index.tsx
src/organisms/schema-form/widgets/date.tsx

feat(date-picker): add disabled prop and simplify CustomDate component

---

src/molecules/filter-component/index.tsx

feat(filter-component): add Clear button to reset filter selection

---

@/components/ui/sonner.tsx
src/molecules/multi-select/index.tsx

feat(multi-select): add disabled prop to MultiSelect component

---

src/organisms/schema-form/custom/label.tsx
src/organisms/schema-form/custom/table-field.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/array.tsx
src/organisms/schema-form/templates/field.tsx
src/organisms/schema-form/templates/object.tsx
src/organisms/schema-form/types/index.ts
src/organisms/schema-form/utils/dependency.ts
src/organisms/schema-form/utils/index.ts
src/organisms/schema-form/widgets/checkbox.tsx
src/organisms/schema-form/widgets/combobox.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx
src/organisms/schema-form/widgets/date.tsx
src/organisms/schema-form/widgets/email.tsx
src/organisms/schema-form/widgets/multi-select.tsx
src/organisms/schema-form/widgets/password.tsx
src/organisms/schema-form/widgets/select.tsx
src/organisms/schema-form/widgets/switch.tsx
src/organisms/schema-form/widgets/text.tsx
src/organisms/schema-form/widgets/textarea.tsx

feat(schema-form): implement dependency-based field options

---

src/organisms/schema-form/templates/field.tsx
src/organisms/schema-form/utils/dependency.ts

fix(schema-form): improve fieldOptions handling and add utility import

---

src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

fix(editable-columns): update data on checked change in tanstack table

---

src/molecules/forms/register-form/index.tsx

feat(register-form): add tenantId field and allow tenant change option

---

src/molecules/tanstack-table/fields/tanstack-table-plain-table.tsx
src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/pinning-styles.ts

feat(tanstack-table): make fillerColumn optional in table props

---

src/organisms/schema-form/templates/field.tsx
src/organisms/schema-form/widgets/combobox.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx
src/organisms/schema-form/widgets/date.tsx
src/organisms/schema-form/widgets/email.tsx
src/organisms/schema-form/widgets/password.tsx
src/organisms/schema-form/widgets/select.tsx
src/organisms/schema-form/widgets/text.tsx
src/organisms/schema-form/widgets/textarea.tsx

feat(SchemaForm): set field value by dependency

---

.github/workflows/publish.yml

chore(publish): update Storybook GitHub Actions to version 1.0.3

---

src/molecules/page-header/index.tsx

feat(PageHeader): enhance navigation logic with pathname check

---

src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx

closes [#1235](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1235)

fix(TanstackTableRowActions): adjust button alignment for better UI

---

src/molecules/date-picker/index.tsx
src/molecules/date-picker/types/index.ts
src/molecules/date-picker/utils/index.ts
src/molecules/tanstack-table/fields/tanstack-table-filter-date.tsx

closes [#1236](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1236)

feat(DatePicker): add DateRangePicker component and utility functions

---

src/molecules/date-picker/utils/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx

fix(columns-by-row-data): simplify faceted item lookup logic & fix(schema-form): invalid iso string

---

src/molecules/tanstack-table/types/index.ts

fix(tanstack-table): update title type to support JSX elements

---

src/organisms/schema-form/fields/index.tsx
src/organisms/schema-form/fields/phone.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/index.tsx
src/organisms/schema-form/widgets/phone.tsx

feat(schema form): add phone input to form

---

src/lib/create-zod-object/index.tsx

feat: export zod and zodResolver for improved schema handling

---

src/molecules/tables/index.tsx
src/molecules/tanstack-table/fields/tanstack-table-row-actions.tsx
src/molecules/tanstack-table/index.tsx
src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/table.tsx

feat(tanstack-table): add row duplication and movement actions

---

src/organisms/schema-form/templates/object.tsx

feat(schema-form): add full column span to FieldLabel component

---

src/molecules/filter-component/index.tsx

feat(filter-component): implement collapsible filter section

---

src/organisms/schema-form/widgets/phone.tsx

fix(schema-form): ensure phone input initializes correctly with empty value

---

src/organisms/tiptap/index.tsx
tiptap/components/BlockEditor/BlockEditor.tsx

chore: tiptap style

---

.turbo/turbo-build.log
tiptap/extensions/ImageBlock/ImageBlock.ts

fix: suprise type fix

---

src/organisms/tiptap/index.tsx
tiptap/components/BlockEditor/BlockEditor.tsx
tiptap/styles/index.css

feat(TipTapEditor, BlockEditor): add mode prop for dynamic styling

---

tiptap/extensions/ImageBlock/components/ImageBlockView.tsx

feat(ImageBlockView): make src prop optional

---

package.json
pnpm-lock.yaml

chore(package): update eslint-plugin-unused-imports to version 3.2.0

---

src/organisms/file-uploader/index.tsx

style(FileUploader): file list styles

---

src/organisms/file-uploader/index.tsx

fix(FileUploader): add separator above file cards

---

src/molecules/confirmation-dialog/index.tsx

feat(ConfirmationDialog): add confirmation dialog component with customizable options

---

@/components/ui/accordion.tsx
package.json
pnpm-lock.yaml
src/organisms/file-uploader/index.tsx

feat: Accordion second child & FileUploader label,description

---

src/organisms/file-uploader/index.tsx

feat(file-uploader): enhance file uploader component with new props and rendering options

---

src/organisms/file-uploader/index.tsx

feat(file-uploader): add collapsible props and enhance layout

---

src/molecules/document-card/index.tsx

feat(document-card): add DocumentCard component with tabbed file list display

---

src/organisms/file-uploader/index.tsx

feat(file-uploader): allow label and description to accept React nodes

---

src/molecules/combobox/index.tsx
src/molecules/select-tabs/index.tsx

fix(combobox): simplify onSelect handler to directly use selected item

---

src/molecules/multi-select/index.tsx
src/organisms/file-uploader/index.tsx

feat(file-uploader): adjust padding and border styling based on file presence

feat(multi-select): add optional badge and disabled state for options

---

src/molecules/gallery/blur-fade.tsx
src/molecules/gallery/gallery.stories.tsx
src/molecules/gallery/index.tsx

feat(gallery): add BlurFade component for animated image transitions

---

src/molecules/gallery/index.tsx

feat(gallery): add lazy loading to images for improved performance

---

package.json
src/hooks/useMediaQuery.ts

feat(hooks): add useMediaQuery hook for responsive design

---

src/molecules/date-picker/date-picker.stories.tsx
src/molecules/date-picker/index.tsx
src/organisms/schema-form/utils/index.ts

fix(date-picker): adjust Date object creation to include time offset

---

src/molecules/document-card/index.tsx

fix(document-card): add onDownloadClick prop to FileTypeForFileCard and implement download button functionality

---

src/templates/tab-layout/index.tsx

fix(tab-layout): ensure active tab is correctly determined with search parameters

---

package.json
pnpm-lock.yaml
src/organisms/schema-form/index.tsx
src/organisms/schema-form/types/index.ts
src/organisms/schema-form/utils/langugage.ts
src/organisms/schema-form/widgets/phone.tsx

For turkish error messages all you have to do is pass locale=tr prop

feat(schema-form): add locale support and integrate AJV for Turkish error messages

---

src/organisms/schema-form/widgets/phone.tsx

fix(schema-form): refactor CustomPhoneField to use props directly and improve phone change handling

---

src/molecules/gallery/index.tsx

fix(gallery): adjust padding and alignment for improved layout

---

src/molecules/gallery/index.tsx

feat(gallery): add support for video media type and enhance media rendering

---

src/molecules/page-header/index.tsx

feat(page-header): enhance styling for title and description in header

---

src/molecules/async-select/index.tsx
src/molecules/filter-component/fields/async-select.tsx
src/molecules/filter-component/fields/date.tsx
src/molecules/filter-component/fields/multi-select.tsx
src/molecules/filter-component/index.tsx

feat(filter-component): add multi-select, async-select, and date fields

---

src/molecules/filter-component/index.tsx

feat(filter-component): add filter guidance content and improve layout in FilterComponent

---

src/organisms/schema-form/index.tsx

fix(schema-form): update onChange handler to conditionally set formData based on useDependency

---

src/organisms/auto-form/fields/phone.tsx
src/organisms/schema-form/widgets/index.tsx

chore: change default iso country code 

---

src/organisms/schema-form/index.tsx
src/organisms/schema-form/templates/index.tsx
src/organisms/schema-form/templates/object.tsx
src/organisms/schema-form/templates/table-array/index.tsx
src/organisms/schema-form/templates/table-array/table-array-object.tsx
src/organisms/schema-form/templates/table-array/table-array.tsx
src/organisms/schema-form/types/index.ts
src/organisms/schema-form/utils/index.ts

feat(SchemaForm):TableArray element

---

src/organisms/document-viewer/controllers.tsx
src/organisms/document-viewer/index.tsx
src/organisms/document-viewer/renderers/index.tsx
src/organisms/document-viewer/renderers/pdf.tsx

feat(document-viewer): Add search functionality to PDF renderer

---

src/organisms/schema-form/templates/table-array/table-array-object.tsx
src/organisms/schema-form/utils/index.ts

fix: crash schemaForm is node has no key named properties

---

src/molecules/combobox/index.tsx

feat(Combobox): refactor trigger classNames structure and improve rendering

---

src/molecules/combobox/index.tsx

fix(Combobox): update classNames structure for list label and add optional list prop

---

package.json
pnpm-lock.yaml

chore: bump react-dropzone version to 14.3.5

---

src/organisms/schema-form/index.tsx

fix: proper handle onChange

---

src/organisms/schema-form/templates/object.tsx
src/organisms/schema-form/templates/table-array/table-array.tsx

chore:update array fields

---

src/organisms/schema-form/index.tsx

fix:hopefully this is fixes formData state

---

src/organisms/schema-form/custom/label.tsx
src/organisms/schema-form/templates/table-array/table-array.tsx

fix: format label text to title case in FieldLabel component

---

src/molecules/charts/area-chart.tsx
src/molecules/charts/bar-chart.tsx
src/molecules/charts/index.tsx
src/molecules/charts/pie-chart.tsx
src/molecules/charts/radar-chart.tsx

feat: export ChartData and ChartConfig types for better type management in chart components

---

src/molecules/tanstack-table/fields/tanstack-table-view-options.tsx

feat: refactor TanstackTableViewOptions to improve action button handling and dropdown menu integration

---

package.json
pnpm-lock.yaml
src/organisms/webcam/index.tsx

feat: add WebcamCapture component with video handling and image capture functionality

---

src/organisms/country-selector/index.tsx

chore: change exports

---

src/organisms/schema-form/custom/label.tsx
src/organisms/schema-form/templates/table-array/table-array-object.tsx
src/organisms/schema-form/templates/table-array/table-array.tsx

style:improve table row styles for editable table

---

src/organisms/schema-form/widgets/custom-combobox.tsx

chore:remove autoSelectFirst prop

---

src/molecules/async-select/index.tsx
src/molecules/date-picker/index.tsx
src/molecules/email-input/email.tsx
src/molecules/multi-select/index.tsx
src/molecules/phone-input/index.tsx
src/organisms/schema-form/index.tsx
src/organisms/schema-form/widgets/checkbox.tsx
src/organisms/schema-form/widgets/combobox.tsx
src/organisms/schema-form/widgets/custom-combobox.tsx
src/organisms/schema-form/widgets/date.tsx
src/organisms/schema-form/widgets/email.tsx
src/organisms/schema-form/widgets/password.tsx
src/organisms/schema-form/widgets/select.tsx
src/organisms/schema-form/widgets/switch.tsx
src/organisms/schema-form/widgets/text.tsx
src/organisms/schema-form/widgets/textarea.tsx

feat:add data-testid

---

@/components/ui/accordion.tsx
@/components/ui/button.tsx
@/components/ui/checkbox.tsx
@/components/ui/command.tsx
@/components/ui/context-menu.tsx
@/components/ui/dropdown-menu.tsx
@/components/ui/input.tsx
@/components/ui/label.tsx
@/components/ui/menubar.tsx
@/components/ui/navigation-menu.tsx
@/components/ui/radio-group.tsx
@/components/ui/select.tsx
@/components/ui/switch.tsx
@/components/ui/textarea.tsx
src/molecules/confirm-dialog/index.tsx
src/organisms/auto-form/fields/custom-combobox.tsx
src/organisms/auto-form/index.tsx

chore:add default data-testid to shadcn components

---

@/components/aria/index.tsx
@/components/aria/number-field.tsx
@/components/ui/form.tsx
package.json

feat:react-aria-components

---

src/molecules/filter-component/index.tsx
src/molecules/phone-input/index.tsx

closes https://github.com/ayasofyazilim-clomerce/unirefund-web/issues/616

feat: Fill PhoneInput from tenant country code & fix console errors

---

src/molecules/tanstack-table/types/index.ts
src/molecules/tanstack-table/utils/columns-by-row-data.tsx
src/molecules/tanstack-table/utils/editable-columns-by-row-data.tsx

chore:update shadcn

---

src/molecules/filter-component/fields/async-select.tsx

fix: ensure closeOnSelect behavior is correctly set based on multiple selection

---

src/molecules/date-picker/index.tsx

fix(DatePicker): update onChange to use tenant time zone for date conversion

---

@/components/ui/dropdown-menu.tsx

fix(DropdownMenu): increase z-index for dropdown menu components
